name: webview_windows
description: A WebView2-powered webview implementation for the Windows platform.
version: 0.2.2
repository: https://github.com/jnschulze/flutter-webview-windows
homepage: https://jns.io

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WebviewWindowsPlugin
