name: html_editor_windows
description: A Html editor build on windows platform empowered by WebView2 library
version: 0.2.2
repository: https://github.com/sherlockvn/flutter-webview-windows
homepage: https://github.com/sherlockvn

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WebviewWindowsPlugin
